name: Output information
on: workflow_dispatch 
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo "${{ toJson(github) }}"
      - name: Output Repository Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
      - name: Output Actor Info
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"